# این فایل تعریف‌کننده Rule-Providerها با فرمت صحیح متنی است
rule-providers:
  ircidr:
    type: http
    behavior: ipcidr
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt"
    path: ./ruleset/ircidr.txt
    interval: 86400
  ir:
    type: http
    behavior: domain
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt"
    path: ./ruleset/ir.txt
    interval: 86400
  ads:
    type: http
    behavior: domain
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/category-ads-all.txt"
    path: ./ruleset/ads.txt
    interval: 86400
  malware:
    type: http
    behavior: domain
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt"
    path: ./ruleset/malware.txt
    interval: 86400
  malware-ip:
    type: http
    behavior: ipcidr
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware-ip.txt"
    path: ./ruleset/malware-ip.txt
    interval: 86400
