dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  nameserver:
    - "https://8.8.8.8/dns-query#✅Select"
  proxy-server-nameserver:
    - "8.8.8.8#DIRECT"
  direct-nameserver:
    - "8.8.8.8#DIRECT"
  direct-nameserver-follow-policy: true
  nameserver-policy:
    "rule-set:ir": "8.8.8.8#DIRECT"
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.lan"
    - "+.local"

# ==========================================
# ==========================================
rule-providers:
  malware:
    type: http
    behavior: domain
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt"
    path: ./ruleset/malware.txt
    interval: 86400
  malware-cidr:
    type: http
    behavior: ipcidr
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware-ip.txt"
    path: ./ruleset/malware-cidr.txt
    interval: 86400
  category-ads-all:
    type: http
    behavior: domain
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/category-ads-all.txt"
    path: ./ruleset/category-ads-all.txt
    interval: 86400
  ir:
    type: http
    behavior: domain
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt"
    path: ./ruleset/ir.txt
    interval: 86400
  ircidr:
    type: http
    behavior: ipcidr
    format: text
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt"
    path: ./ruleset/ircidr.txt
    interval: 86400
